### ISSUE TITLE
Dashboard Orgs

### ISSUE THREAD

**Issue by aayush-ag21** [grafana-wizzy/wizzy#157]
I am currently using Grafana v6.3 on localhost and wizzy 0.6.0.
When I use the command wizzy summarize dashboard ,It shows that I have 0 rows,whereas I actually have 2.
Panels are not being listed either. However Datasource is being showed.
On wizzy import orgs I get a 403 error.
Is 6.3 not supported as of now or am I skipping a step?

**Comment by Sytten** [comment]
I am in the process of updating the software since I just got maintenance access a few weeks ago. I still dont have npm access so I can't publish bug fixes yet.
If you want to help me, pull the latest code and try again each command. If you can have reproducible steps for me that would also be helpful.

**Comment by Sytten** [comment]
For `wizzy import orgs`, your user needs to have access to the server configuration. API keys will not work.

**Comment by aayush-ag21** [comment]
Okay, Thank you I'll look into it.
